### ISSUE TITLE
[Feature]Add observedGeneration to represent Workload has reconciled

### ISSUE THREAD

**Issue by Ghostbaby** [cen-ngc5139/zookeeper-operator#34]
**Is your feature request related to a problem? Please describe.**
`observedGeneration` field of status in K8s object is widely used in K8s built-in resource. It reflects the generation of the most recently observed Object.

With the help of observedGeneration field, user can recognize whether a CR is reconciled by controller.

A workflow will like below:
```yaml
apiVersion: cache.ghostbaby.io/v1alpha1
kind: Workload
metadata:
  name: workload-sample
  namespace: pg
spec:
  version: v3.5.6
  replicas: 5
  ...
```

After the controller reconciled, the observedGeneration will appear and align with generation in metadata:
```yaml
apiVersion: cache.ghostbaby.io/v1alpha1
kind: Workload
metadata:
  name: workload-sample
  namespace: pg
  generation: 1
spec:
  version: v3.5.6
  replicas: 5
  ...
status:
  observedGeneration: 1
```

Later, we have another change, it will be:
```yaml
apiVersion: cache.ghostbaby.io/v1alpha1
kind: Workload
metadata:
  name: workload-sample
  namespace: pg
  generation: 2
spec:
  version: v3.5.7
  replicas: 5
  ...
status:
  observedGeneration: 1
```

And after reconciled, it will be:
```yaml
apiVersion: cache.ghostbaby.io/v1alpha1
kind: Workload
metadata:
  name: workload-sample
  namespace: pg
  generation: 2
spec:
  version: v3.5.7
  replicas: 5
  ...
status:
  observedGeneration: 2
```
