### ISSUE TITLE
[BUG] mutate webhook not work

### ISSUE THREAD

**Issue by Ghostbaby** [cen-ngc5139/zookeeper-operator#48]
**Describe the bug**
```yaml
apiVersion: zk.cache.ghostbaby.io/v1alpha1
kind: Workload
metadata:
  name: workload-sample
spec:
  version: v3.5.6
  replicas: 3
  cluster:
    name: test
    exporter:
      exporter: true
      exporterImage: ghostbaby/zookeeper_exporter
      exporterVersion: v3.5.6
      disableExporterProbes: false
    storage:
      persistentVolumeClaim:
        metadata:
          name: zookeeper-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```
when I use this YAML file to create zk cluster, mutate webhook not work .
